#include <stdbool.h>
#include "constants.h"

// Errors
const char* error_messages[256] =
{
  "GENERAL_NO_ERROR", // 0
  "GENERAL_UNDEFINED_ERROR", // 1
  "GENERAL_UNDEFINED_ERROR", // 2
  "GENERAL_UNDEFINED_ERROR", // 3
  "GENERAL_UNDEFINED_ERROR", // 4
  "GENERAL_UNDEFINED_ERROR", // 5
  "GENERAL_UNDEFINED_ERROR", // 6
  "GENERAL_UNDEFINED_ERROR", // 7
  "GENERAL_UNDEFINED_ERROR", // 8
  "GENERAL_UNEXPECTED_ERROR", // 9
  "COMMAND_NO_ERROR", // 10
  "COMMAND_NO_INPUT", // 11
  "COMMAND_DOES_NOT_EXIST", // 12
  "COMMAND_INSUFFICIENT_ARGUMENT_DATA", // 13
  "COMMAND_EXCESSIVE_ARGUMENT_DATA", // 14
  "COMMAND_UNDEFINED_ERROR", // 15
  "COMMAND_UNDEFINED_ERROR", // 16
  "COMMAND_UNDEFINED_ERROR", // 17
  "COMMAND_UNDEFINED_ERROR", // 18
  "COMMAND_UNEXPECTED_ERROR", // 19
  "START_GAME_NO_ERROR", // 20
  "START_GAME_ALREADY_IN_PROGRESS", // 21
  "START_GAME_HEIGHT_TOO_SMALL", // 22
  "START_GAME_HEIGHT_TOO_LARGE", // 23
  "START_GAME_WIDTH_TOO_SMALL", // 24
  "START_GAME_WIDTH_TOO_LARGE", // 25
  "START_GAME_NOT_ENOUGH_MINES", // 26
  "START_GAME_TOO_MANY_MINES", // 27
  "START_GAME_UNDEFINED_ERROR", // 28
  "START_GAME_UNEXPECTED_ERROR", // 29
  "SYNC_GAME_NO_ERROR", // 30
  "SYNC_GAME_NOT_IN_PROGRESS", // 31
  "SYNC_GAME_UNDEFINED_ERROR", // 32
  "SYNC_GAME_UNDEFINED_ERROR", // 33
  "SYNC_GAME_UNDEFINED_ERROR", // 34
  "SYNC_GAME_UNDEFINED_ERROR", // 35
  "SYNC_GAME_UNDEFINED_ERROR", // 36
  "SYNC_GAME_UNDEFINED_ERROR", // 37
  "SYNC_GAME_UNDEFINED_ERROR", // 38
  "SYNC_GAME_UNEXPECTED_ERROR", // 39
  "REVEAL_NO_ERROR", // 40
  "REVEAL_GAME_NOT_IN_PROGRESS", // 41
  "REVEAL_GAME_ALREADY_FINISHED", // 42
  "REVEAL_X_COORDINATE_TOO_LOW", // 43
  "REVEAL_X_COORDINATE_TOO_HIGH", // 44
  "REVEAL_Y_COORDINATE_TOO_LOW", // 45
  "REVEAL_Y_COORDINATE_TOO_HIGH", // 46
  "REVEAL_MUST_BE_UNREVEALED", // 47
  "REVEAL_MUST_UNFLAG_FIRST", // 48
  "REVEAL_UNEXPECTED_ERROR", // 49
  "TOGGLE_FLAG_NO_ERROR", // 50
  "TOGGLE_FLAG_GAME_NOT_IN_PROGRESS", // 51
  "TOGGLE_FLAG_GAME_ALREADY_FINISHED", // 52
  "TOGGLE_FLAG_X_COORDINATE_TOO_LOW", // 53
  "TOGGLE_FLAG_X_COORDINATE_TOO_HIGH", // 54
  "TOGGLE_FLAG_Y_COORDINATE_TOO_LOW", // 55
  "TOGGLE_FLAG_Y_COORDINATE_TOO_HIGH", // 56
  "TOGGLE_FLAG_MUST_BE_UNREVEALED", // 57
  "TOGGLE_FLAG_UNDEFINED_ERROR", // 58
  "TOGGLE_FLAG_UNEXPECTED_ERROR", // 59
  "QUIT_GAME_NO_ERROR", // 60
  "QUIT_GAME_NOT_IN_PROGRESS", // 61
  "QUIT_GAME_UNDEFINED_ERROR", // 62
  "QUIT_GAME_UNDEFINED_ERROR", // 63
  "QUIT_GAME_UNDEFINED_ERROR", // 64
  "QUIT_GAME_UNDEFINED_ERROR", // 65
  "QUIT_GAME_UNDEFINED_ERROR", // 66
  "QUIT_GAME_UNDEFINED_ERROR", // 67
  "QUIT_GAME_UNDEFINED_ERROR", // 68
  "QUIT_GAME_UNEXPECTED_ERROR", // 69
  "SHUT_DOWN_NO_ERROR", // 70
  "SHUT_DOWN_UNDEFINED_ERROR", // 71
  "SHUT_DOWN_UNDEFINED_ERROR", // 72
  "SHUT_DOWN_UNDEFINED_ERROR", // 73
  "SHUT_DOWN_UNDEFINED_ERROR", // 74
  "SHUT_DOWN_UNDEFINED_ERROR", // 75
  "SHUT_DOWN_UNDEFINED_ERROR", // 76
  "SHUT_DOWN_UNDEFINED_ERROR", // 77
  "SHUT_DOWN_UNDEFINED_ERROR", // 78
  "SHUT_DOWN_UNEXPECTED_ERROR", // 79
  "UNDEFINED_ERROR", // 80
  "UNDEFINED_ERROR", // 81
  "UNDEFINED_ERROR", // 82
  "UNDEFINED_ERROR", // 83
  "UNDEFINED_ERROR", // 84
  "UNDEFINED_ERROR", // 85
  "UNDEFINED_ERROR", // 86
  "UNDEFINED_ERROR", // 87
  "UNDEFINED_ERROR", // 88
  "UNDEFINED_ERROR", // 89
  "UNDEFINED_ERROR", // 90
  "UNDEFINED_ERROR", // 91
  "UNDEFINED_ERROR", // 92
  "UNDEFINED_ERROR", // 93
  "UNDEFINED_ERROR", // 94
  "UNDEFINED_ERROR", // 95
  "UNDEFINED_ERROR", // 96
  "UNDEFINED_ERROR", // 97
  "UNDEFINED_ERROR", // 98
  "UNDEFINED_ERROR", // 99
  "UNDEFINED_ERROR", // 100
  "UNDEFINED_ERROR", // 101
  "UNDEFINED_ERROR", // 102
  "UNDEFINED_ERROR", // 103
  "UNDEFINED_ERROR", // 104
  "UNDEFINED_ERROR", // 105
  "UNDEFINED_ERROR", // 106
  "UNDEFINED_ERROR", // 107
  "UNDEFINED_ERROR", // 108
  "UNDEFINED_ERROR", // 109
  "UNDEFINED_ERROR", // 110
  "UNDEFINED_ERROR", // 111
  "UNDEFINED_ERROR", // 112
  "UNDEFINED_ERROR", // 113
  "UNDEFINED_ERROR", // 114
  "UNDEFINED_ERROR", // 115
  "UNDEFINED_ERROR", // 116
  "UNDEFINED_ERROR", // 117
  "UNDEFINED_ERROR", // 118
  "UNDEFINED_ERROR", // 119
  "UNDEFINED_ERROR", // 120
  "UNDEFINED_ERROR", // 121
  "UNDEFINED_ERROR", // 122
  "UNDEFINED_ERROR", // 123
  "UNDEFINED_ERROR", // 124
  "UNDEFINED_ERROR", // 125
  "UNDEFINED_ERROR", // 126
  "UNDEFINED_ERROR", // 127
  "UNDEFINED_ERROR", // 128
  "UNDEFINED_ERROR", // 129
  "UNDEFINED_ERROR", // 130
  "UNDEFINED_ERROR", // 131
  "UNDEFINED_ERROR", // 132
  "UNDEFINED_ERROR", // 133
  "UNDEFINED_ERROR", // 134
  "UNDEFINED_ERROR", // 135
  "UNDEFINED_ERROR", // 136
  "UNDEFINED_ERROR", // 137
  "UNDEFINED_ERROR", // 138
  "UNDEFINED_ERROR", // 139
  "UNDEFINED_ERROR", // 140
  "UNDEFINED_ERROR", // 141
  "UNDEFINED_ERROR", // 142
  "UNDEFINED_ERROR", // 143
  "UNDEFINED_ERROR", // 144
  "UNDEFINED_ERROR", // 145
  "UNDEFINED_ERROR", // 146
  "UNDEFINED_ERROR", // 147
  "UNDEFINED_ERROR", // 148
  "UNDEFINED_ERROR", // 149
  "UNDEFINED_ERROR", // 150
  "UNDEFINED_ERROR", // 151
  "UNDEFINED_ERROR", // 152
  "UNDEFINED_ERROR", // 153
  "UNDEFINED_ERROR", // 154
  "UNDEFINED_ERROR", // 155
  "UNDEFINED_ERROR", // 156
  "UNDEFINED_ERROR", // 157
  "UNDEFINED_ERROR", // 158
  "UNDEFINED_ERROR", // 159
  "UNDEFINED_ERROR", // 160
  "UNDEFINED_ERROR", // 161
  "UNDEFINED_ERROR", // 162
  "UNDEFINED_ERROR", // 163
  "UNDEFINED_ERROR", // 164
  "UNDEFINED_ERROR", // 165
  "UNDEFINED_ERROR", // 166
  "UNDEFINED_ERROR", // 167
  "UNDEFINED_ERROR", // 168
  "UNDEFINED_ERROR", // 169
  "UNDEFINED_ERROR", // 170
  "UNDEFINED_ERROR", // 171
  "UNDEFINED_ERROR", // 172
  "UNDEFINED_ERROR", // 173
  "UNDEFINED_ERROR", // 174
  "UNDEFINED_ERROR", // 175
  "UNDEFINED_ERROR", // 176
  "UNDEFINED_ERROR", // 177
  "UNDEFINED_ERROR", // 178
  "UNDEFINED_ERROR", // 179
  "UNDEFINED_ERROR", // 180
  "UNDEFINED_ERROR", // 181
  "UNDEFINED_ERROR", // 182
  "UNDEFINED_ERROR", // 183
  "UNDEFINED_ERROR", // 184
  "UNDEFINED_ERROR", // 185
  "UNDEFINED_ERROR", // 186
  "UNDEFINED_ERROR", // 187
  "UNDEFINED_ERROR", // 188
  "UNDEFINED_ERROR", // 189
  "UNDEFINED_ERROR", // 190
  "UNDEFINED_ERROR", // 191
  "UNDEFINED_ERROR", // 192
  "UNDEFINED_ERROR", // 193
  "UNDEFINED_ERROR", // 194
  "UNDEFINED_ERROR", // 195
  "UNDEFINED_ERROR", // 196
  "UNDEFINED_ERROR", // 197
  "UNDEFINED_ERROR", // 198
  "UNDEFINED_ERROR", // 199
  "UNDEFINED_ERROR", // 200
  "UNDEFINED_ERROR", // 201
  "UNDEFINED_ERROR", // 202
  "UNDEFINED_ERROR", // 203
  "UNDEFINED_ERROR", // 204
  "UNDEFINED_ERROR", // 205
  "UNDEFINED_ERROR", // 206
  "UNDEFINED_ERROR", // 207
  "UNDEFINED_ERROR", // 208
  "UNDEFINED_ERROR", // 209
  "UNDEFINED_ERROR", // 210
  "UNDEFINED_ERROR", // 211
  "UNDEFINED_ERROR", // 212
  "UNDEFINED_ERROR", // 213
  "UNDEFINED_ERROR", // 214
  "UNDEFINED_ERROR", // 215
  "UNDEFINED_ERROR", // 216
  "UNDEFINED_ERROR", // 217
  "UNDEFINED_ERROR", // 218
  "UNDEFINED_ERROR", // 219
  "UNDEFINED_ERROR", // 220
  "UNDEFINED_ERROR", // 221
  "UNDEFINED_ERROR", // 222
  "UNDEFINED_ERROR", // 223
  "UNDEFINED_ERROR", // 224
  "UNDEFINED_ERROR", // 225
  "UNDEFINED_ERROR", // 226
  "UNDEFINED_ERROR", // 227
  "UNDEFINED_ERROR", // 228
  "UNDEFINED_ERROR", // 229
  "UNDEFINED_ERROR", // 230
  "UNDEFINED_ERROR", // 231
  "UNDEFINED_ERROR", // 232
  "UNDEFINED_ERROR", // 233
  "UNDEFINED_ERROR", // 234
  "UNDEFINED_ERROR", // 235
  "UNDEFINED_ERROR", // 236
  "UNDEFINED_ERROR", // 237
  "UNDEFINED_ERROR", // 238
  "UNDEFINED_ERROR", // 239
  "UNDEFINED_ERROR", // 240
  "UNDEFINED_ERROR", // 241
  "UNDEFINED_ERROR", // 242
  "UNDEFINED_ERROR", // 243
  "UNDEFINED_ERROR", // 244
  "UNDEFINED_ERROR", // 245
  "UNDEFINED_ERROR", // 246
  "UNDEFINED_ERROR", // 247
  "UNDEFINED_ERROR", // 248
  "UNDEFINED_ERROR", // 249
  "UNDEFINED_ERROR", // 250
  "UNDEFINED_ERROR", // 251
  "UNDEFINED_ERROR", // 252
  "UNDEFINED_ERROR", // 253
  "UNDEFINED_ERROR", // 254
  "UNDEFINED_ERROR" // 255
};

// Characters.
const unsigned char BITS_PER_CHAR = 8;
const unsigned char CHAR_SPACE = 32;
const unsigned char CONTROL_CHARACTER_RANGE = 31;
const unsigned char DATA_TO_CHARACTER_OFFSET = 48;

// Transmission info.
const unsigned short MAXIMUM_POSSIBLE_COMMAND_LENGTH = 5;
const unsigned short MAXIMUM_POSSIBLE_RESPONSE_LENGTH = 2136;

// Bit flags for position scheme.
const unsigned char BITS_ADJACENT = 0xfu;   // 0b00001111
const unsigned char BIT_MINED = 0x10u;      // 0b00010000
const unsigned char BITS_SENSITIVE = 0x1fu; // 0b00011111
const unsigned char BIT_FLAGGED = 0x20u;    // 0b00100000
const unsigned char BIT_REVEALED = 0x40u;   // 0b01000000
const unsigned char BIT_UNUSED = 0x80u;     // 0b10000000

// Parameter constraints for new game.
const unsigned char NEW_GAME_MIN_HEIGHT = 9;
const unsigned char NEW_GAME_MIN_WIDTH = 9;
const unsigned char NEW_GAME_MAX_HEIGHT = 24;
const unsigned char NEW_GAME_MAX_WIDTH = 30;
const unsigned char NEW_GAME_MIN_MINES = 10;

