#include "common_constants.h"

// Buffer lengths.
const unsigned int COMMAND_BUFFER_LENGTH = 1048580;
const unsigned int RESPONSE_BUFFER_LENGTH = 1048580;

// Command lengths and offsets.
const unsigned char COMMAND_START_GAME_REQUIRED_LENGTH = 5;
const unsigned char COMMAND_START_GAME_HEIGHT_OFFSET = 1;
const unsigned char COMMAND_START_GAME_WIDTH_OFFSET = 2;
const unsigned char COMMAND_START_GAME_MINES_OFFSET = 3;
const unsigned char COMMAND_SYNC_GAME_REQUIRED_LENGTH = 1;
const unsigned char COMMAND_REVEAL_POSITION_REQUIRED_LENGTH = 3;
const unsigned char COMMAND_REVEAL_POSITION_X_OFFSET = 1;
const unsigned char COMMAND_REVEAL_POSITION_Y_OFFSET = 2;
const unsigned char COMMAND_TOGGLE_FLAG_REQUIRED_LENGTH = 3;
const unsigned char COMMAND_TOGGLE_FLAG_X_OFFSET = 1;
const unsigned char COMMAND_TOGGLE_FLAG_Y_OFFSET = 2;
const unsigned char COMMAND_QUIT_GAME_REQUIRED_LENGTH = 1;
const unsigned char COMMAND_DISCONNECT_CLIENT_REQUIRED_LENGTH = 1;
const unsigned char COMMAND_SHUT_DOWN_REQUIRED_LENGTH = 1;

// Response lengths and offsets.
const unsigned char RESPONSE_START_GAME_REQUIRED_LENGTH = 1;
const unsigned char RESPONSE_SYNC_GAME_REQUIRED_LENGTH = 6;
const unsigned char RESPONSE_SYNC_GAME_GAME_STATUS_OFFSET = 1;
const unsigned char RESPONSE_SYNC_GAME_HEIGHT_OFFSET = 2;
const unsigned char RESPONSE_SYNC_GAME_WIDTH_OFFSET = 3;
const unsigned char RESPONSE_SYNC_GAME_MINES_OFFSET = 4;
const unsigned char RESPONSE_SYNC_GAME_FIELD_COPY_OFFSET = 6;
const unsigned char RESPONSE_REVEAL_POSITION_REQUIRED_LENGTH = 2;
const unsigned char RESPONSE_REVEAL_POSITION_GAME_STATUS_OFFSET = 1;
const unsigned char RESPONSE_REVEAL_POSITION_MBLA_HEAD_OFFSET = 2;
const unsigned char RESPONSE_TOGGLE_FLAG_REQUIRED_LENGTH = 1;
const unsigned char RESPONSE_TOGGLE_FLAG_MBLA_HEAD_OFFSET = 1;
const unsigned char RESPONSE_QUIT_GAME_REQUIRED_LENGTH = 1;
const unsigned char RESPONSE_DISCONNECT_CLIENT_REQUIRED_LENGTH = 1;
const unsigned char RESPONSE_SHUT_DOWN_REQUIRED_LENGTH = 1;

// Copy node length and offsets.
const unsigned char COPY_NODE_REQUIRED_LENGTH = 3;
const unsigned char COPY_NODE_X_OFFSET = 0;
const unsigned char COPY_NODE_Y_OFFSET = 1;
const unsigned char COPY_NODE_POSITION_OFFSET = 2;

// Bit flags for position scheme.
const unsigned char BITS_ADJACENT = 0x0fu;  // 0b00001111
const unsigned char BIT_MINED = 0x10u;      // 0b00010000
const unsigned char BITS_SENSITIVE = 0x1fu; // 0b00011111
const unsigned char BIT_FLAGGED = 0x20u;    // 0b00100000
const unsigned char BIT_REVEALED = 0x40u;   // 0b01000000
const unsigned char BIT_UNUSED = 0x80u;     // 0b10000000

// Parameter constraints for new game.
const unsigned char NEW_GAME_MIN_HEIGHT = 9;
const unsigned char NEW_GAME_MIN_WIDTH = 9;
const unsigned char NEW_GAME_MAX_HEIGHT = 24;
const unsigned char NEW_GAME_MAX_WIDTH = 30;
const unsigned char NEW_GAME_MIN_MINES = 10;

// Miscellaneous.
const unsigned char GENERAL_NO_ERROR = 0;
const unsigned char BITS_PER_CHAR = 8;
const unsigned char CHAR_SPACE = 32;
const unsigned char CONTROL_CHARACTER_RANGE = 31;
const unsigned char DATA_TO_CHARACTER_OFFSET = 48;
const unsigned char SUPPORTED_COMMAND_COUNT = 6;
const unsigned char RESPONSE_CODE_GROUP_WIDTH = 10;
const unsigned char RESPONSE_CODE_OUT_OF_MEMORY_INDICATOR = 9;
const unsigned short SERVER_MAX_CONNECTIONS = 1;
const unsigned short SERVER_PORT_NUMBER = 54321;
const unsigned int CLIENT_RECEIVE_OPTIONS = 0;
const unsigned int CLIENT_SEND_OPTIONS = 0;
const unsigned int SERVER_RECEIVE_OPTIONS = 0;
const unsigned int SERVER_SEND_OPTIONS = 0;
const char* SERVER_ADDRESS = "127.0.0.1";

// Response code strings.
const char* response_code_strings[RESPONSE_CODE_COUNT] =
{
  "START_GAME_NO_ERROR", // 0
  "START_GAME_ALREADY_IN_PROGRESS", // 1
  "START_GAME_HEIGHT_TOO_SMALL", // 2
  "START_GAME_HEIGHT_TOO_LARGE", // 3
  "START_GAME_WIDTH_TOO_SMALL", // 4
  "START_GAME_WIDTH_TOO_LARGE", // 5
  "START_GAME_NOT_ENOUGH_MINES", // 6
  "START_GAME_TOO_MANY_MINES", // 7
  "START_GAME_UNDEFINED_ERROR", // 8
  "START_GAME_OUT_OF_MEMORY", // 9
  "SYNC_GAME_NO_ERROR", // 10
  "SYNC_GAME_NOT_IN_PROGRESS", // 11
  "SYNC_GAME_UNDEFINED_ERROR", // 12
  "SYNC_GAME_UNDEFINED_ERROR", // 13
  "SYNC_GAME_UNDEFINED_ERROR", // 14
  "SYNC_GAME_UNDEFINED_ERROR", // 15
  "SYNC_GAME_UNDEFINED_ERROR", // 16
  "SYNC_GAME_UNDEFINED_ERROR", // 17
  "SYNC_GAME_UNDEFINED_ERROR", // 18
  "SYNC_GAME_OUT_OF_MEMORY", // 19
  "REVEAL_POSITION_NO_ERROR", // 20
  "REVEAL_POSITION_GAME_NOT_IN_PROGRESS", // 21
  "REVEAL_POSITION_GAME_ALREADY_FINISHED", // 22
  "REVEAL_POSITION_X_COORDINATE_TOO_LOW", // 23
  "REVEAL_POSITION_X_COORDINATE_TOO_HIGH", // 24
  "REVEAL_POSITION_MUST_BE_UNREVEALED", // 25
  "REVEAL_POSITION_MUST_UNFLAG_FIRST", // 26
  "REVEAL_POSITION_UNDEFINED_ERROR", // 27
  "REVEAL_POSITION_UNDEFINED_ERROR", // 28
  "REVEAL_POSITION_OUT_OF_MEMORY", // 29
  "TOGGLE_FLAG_NO_ERROR", // 30
  "TOGGLE_FLAG_GAME_NOT_IN_PROGRESS", // 31
  "TOGGLE_FLAG_GAME_ALREADY_FINISHED", // 32
  "TOGGLE_FLAG_X_COORDINATE_TOO_LOW", // 33
  "TOGGLE_FLAG_X_COORDINATE_TOO_HIGH", // 34
  "TOGGLE_FLAG_Y_COORDINATE_TOO_LOW", // 35
  "TOGGLE_FLAG_Y_COORDINATE_TOO_HIGH", // 36
  "TOGGLE_FLAG_MUST_BE_UNREVEALED", // 37
  "TOGGLE_FLAG_UNDEFINED_ERROR", // 38
  "TOGGLE_FLAG_OUT_OF_MEMORY", // 39
  "QUIT_GAME_NO_ERROR", // 40
  "QUIT_GAME_NOT_IN_PROGRESS", // 41
  "QUIT_GAME_UNDEFINED_ERROR", // 42
  "QUIT_GAME_UNDEFINED_ERROR", // 43
  "QUIT_GAME_UNDEFINED_ERROR", // 44
  "QUIT_GAME_UNDEFINED_ERROR", // 45
  "QUIT_GAME_UNDEFINED_ERROR", // 46
  "QUIT_GAME_UNDEFINED_ERROR", // 47
  "QUIT_GAME_UNDEFINED_ERROR", // 48
  "QUIT_GAME_OUT_OF_MEMORY", // 49
  "DISCONNECT_CLIENT_NO_ERROR", // 50
  "DISCONNECT_CLIENT_UNDEFINED_ERROR", // 51
  "DISCONNECT_CLIENT_UNDEFINED_ERROR", // 52
  "DISCONNECT_CLIENT_UNDEFINED_ERROR", // 53
  "DISCONNECT_CLIENT_UNDEFINED_ERROR", // 54
  "DISCONNECT_CLIENT_UNDEFINED_ERROR", // 55
  "DISCONNECT_CLIENT_UNDEFINED_ERROR", // 56
  "DISCONNECT_CLIENT_UNDEFINED_ERROR", // 57
  "DISCONNECT_CLIENT_UNDEFINED_ERROR", // 58
  "DISCONNECT_CLIENT_OUT_OF_MEMORY", // 59
  "SHUT_DOWN_NO_ERROR", // 60
  "SHUT_DOWN_UNDEFINED_ERROR", // 61
  "SHUT_DOWN_UNDEFINED_ERROR", // 62
  "SHUT_DOWN_UNDEFINED_ERROR", // 63
  "SHUT_DOWN_UNDEFINED_ERROR", // 64
  "SHUT_DOWN_UNDEFINED_ERROR", // 65
  "SHUT_DOWN_UNDEFINED_ERROR", // 66
  "SHUT_DOWN_UNDEFINED_ERROR", // 67
  "SHUT_DOWN_UNDEFINED_ERROR", // 68
  "SHUT_DOWN_OUT_OF_MEMORY", // 69
  "COMMAND_NO_ERROR", // 70
  "COMMAND_NO_INPUT", // 71
  "COMMAND_CODE_NOT_VALID", // 72
  "COMMAND_INSUFFICIENT_DATA", // 73
  "COMMAND_EXCESSIVE_DATA", // 74
  "COMMAND_UNDEFINED_ERROR", // 75
  "COMMAND_UNDEFINED_ERROR", // 76
  "COMMAND_UNDEFINED_ERROR", // 77
  "COMMAND_UNDEFINED_ERROR", // 78
  "COMMAND_OUT_OF_MEMORY", // 79
  "CLIENT_NO_ERROR", // 80
  "CLIENT_SOCKET_CREATION_FAILED", // 81
  "CLIENT_SERVER_ADDRESS_CONVERSION_FAILED", // 82
  "CLIENT_CONNECTION_TO_SERVER_FAILED", // 83
  "CLIENT_UNDEFINED_ERROR", // 84
  "CLIENT_UNDEFINED_ERROR", // 85
  "CLIENT_UNDEFINED_ERROR", // 86
  "CLIENT_UNDEFINED_ERROR", // 87
  "CLIENT_UNDEFINED_ERROR", // 88
  "CLIENT_OUT_OF_MEMORY", // 89
  "SERVER_NO_ERROR", // 90
  "SERVER_SOCKET_CREATION_FAILED", // 91
  "SERVER_SOCKET_BIND_FAILED", // 92
  "SERVER_SOCKET_LISTEN_FAILED", // 93
  "SERVER_UNDEFINED_ERROR", // 94
  "SERVER_UNDEFINED_ERROR", // 95
  "SERVER_UNDEFINED_ERROR", // 96
  "SERVER_UNDEFINED_ERROR", // 97
  "SERVER_UNDEFINED_ERROR", // 98
  "PROGRAM_OUT_OF_MEMORY" // 99
};

// Game status strings.
const char* game_status_strings[5] =
{
  "NOT_IN_PROGRESS", // 0
  "IN_PROGRESS_NO_REVEAL", // 1
  "IN_PROGRESS", // 2
  "LOST", // 3
  "WON" // 4
};

