#ifndef COMMON_ENUMS_H
#define COMMON_ENUMS_H

// Endian modes.
typedef enum byte_order
{
  // Technically there are other types of endian byte orders which are utilized on ancient and exotic systems such as
  // the Univac, LINC, or PDP-6.  These systems often utilize signed magnitude or 1's complement instead of 2's
  // complement for storing bits and follow an inverted byte order for negative values.  It is extremely unlikely that
  // this program will ever be run on such a machine.  In the unforseen event that it is we will add other types to
  // this enum and add supporting utility functions then.
  ENDIAN_LITTLE,
  ENDIAN_BIG
} Byte_order;

// Commands types.
typedef enum command_type
{
  COMMAND_START_GAME = 0,
  COMMAND_SYNC_GAME = 1,
  COMMAND_REVEAL_POSITION = 2,
  COMMAND_TOGGLE_FLAG = 3,
  COMMAND_QUIT_GAME = 4,
  COMMAND_DISCONNECT_CLIENT = 5,
  COMMAND_SHUT_DOWN = 6
} Command_type;

// Response codes.
typedef enum response_code
{
  START_GAME_NO_ERROR = 0,
  START_GAME_ALREADY_IN_PROGRESS = 1,
  START_GAME_HEIGHT_TOO_SMALL = 2,
  START_GAME_HEIGHT_TOO_LARGE = 3,
  START_GAME_WIDTH_TOO_SMALL = 4,
  START_GAME_WIDTH_TOO_LARGE = 5,
  START_GAME_NOT_ENOUGH_MINES = 6,
  START_GAME_TOO_MANY_MINES = 7,
  START_GAME_OUT_OF_MEMORY = 9,
  SYNC_GAME_NO_ERROR = 10,
  SYNC_GAME_NOT_IN_PROGRESS = 11,
  SYNC_GAME_OUT_OF_MEMORY = 19,
  REVEAL_POSITION_NO_ERROR = 20,
  REVEAL_POSITION_GAME_NOT_IN_PROGRESS = 21,
  REVEAL_POSITION_GAME_ALREADY_FINISHED = 22,
  REVEAL_POSITION_X_COORDINATE_TOO_HIGH = 23,
  REVEAL_POSITION_Y_COORDINATE_TOO_HIGH = 24,
  REVEAL_POSITION_MUST_BE_UNREVEALED = 25,
  REVEAL_POSITION_MUST_UNFLAG_FIRST = 26,
  REVEAL_POSITION_OUT_OF_MEMORY = 29,
  TOGGLE_FLAG_NO_ERROR = 30,
  TOGGLE_FLAG_GAME_NOT_IN_PROGRESS = 31,
  TOGGLE_FLAG_GAME_ALREADY_FINISHED = 32,
  TOGGLE_FLAG_X_COORDINATE_TOO_HIGH = 33,
  TOGGLE_FLAG_Y_COORDINATE_TOO_HIGH = 34,
  TOGGLE_FLAG_MUST_BE_UNREVEALED = 35,
  TOGGLE_FLAG_OUT_OF_MEMORY = 36,
  QUIT_GAME_NO_ERROR = 40,
  QUIT_GAME_NOT_IN_PROGRESS = 41,
  QUIT_GAME_OUT_OF_MEMORY = 49,
  DISCONNECT_CLIENT_NO_ERROR = 50,
  DISCONNECT_CLIENT_OUT_OF_MEMORY = 59,
  SHUT_DOWN_NO_ERROR = 60,
  SHUT_DOWN_OUT_OF_MEMORY = 69,
  COMMAND_NO_INPUT = 71,
  COMMAND_CODE_NOT_VALID = 72,
  COMMAND_INSUFFICIENT_DATA = 73,
  COMMAND_EXCESSIVE_DATA = 74,
  CLIENT_NO_ERROR = 80,
  CLIENT_SOCKET_CREATION_FAILED = 81,
  CLIENT_SERVER_ADDRESS_CONVERSION_FAILED = 82,
  CLIENT_CONNECTION_TO_SERVER_FAILED = 83,
  CLIENT_OUT_OF_MEMORY = 89,
  SERVER_NO_ERROR = 90,
  SERVER_SOCKET_CREATION_FAILED = 91,
  SERVER_SOCKET_BIND_FAILED = 92,
  SERVER_SOCKET_LISTEN_FAILED = 93,
  SERVER_OUT_OF_MEMORY = 99
} Response_code;

// Game statuses.
typedef enum game_status
{
  GAME_STATUS_NOT_IN_PROGRESS = 0,
  GAME_STATUS_IN_PROGRESS_NO_REVEAL = 1,
  GAME_STATUS_IN_PROGRESS = 2,
  GAME_STATUS_LOST = 3,
  GAME_STATUS_WON = 4
} Game_status;

#endif // COMMON_ENUMS_H

